apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: todo-analytics
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: rmq-1
  params:
    - name: run-image
      value: harbor.apps.cf.tanzutime.com/apps/todo-analytics
  source:
    git:
      url: https://github.com/odedia/todo-analytics
      ref:
        branch: main
